version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/home/app
      - ./docker/nginx/conf/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 80:80
    links:
      - php

  php:
    build: docker/php
    working_dir: /home/app
    volumes:
      - .:/home/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - .:/home/app
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

  quality-assurance:
    build: docker/quality-assurance
    volumes:
      - .:/project